### ISSUE TITLE
Verification of g^{y}

### ISSUE THREAD

**Issue by shazly333** [HSG88/eVoting#1]
I have read the paper and seen your implementation and I would appreciate if you could please clarify the following:

Since I have seen your improvement on McCorry's implementation, I noticed that you don't check if g^{y} is computed correctly or not. Hence, any voter can generate any g^{y} and makes his zkp then generates a1, b1, a2, b2. 

Your zkp verifies only if the vote is **formed** correctly but it doesn't verify if it is calculated correctly.

McCorry's implementation reduced his scalability to be around 50 voters because it generates g^{y} for each voter but in your implementation, you delegate this part to the voter and he can compute it wrongly without any checking by the contract on it. 

McCorry's implementation generates g^{y} for each voter so that it can verify the vote is **formed** and **calculated** correctly and doesn't use g^{y} generated by the voter in his verification of the proof.

If you verify in your code that g^{y} is calculated correctly please can you show me how?

Thanks in advance.

**Comment by HSG88** [comment]
Hello, 
Sorry for the late reply. In this implementation, there is no way for the smart contract to check the validity of `Y = g^y` submitted by voters at the function `castVote`. 

My initial thought to efficiently resolve this issue (i.e., not compute them by the smart contract) is to have the admin compute Y_i for all voters and: 
1. Publish them on IPFS that is bridged it to the smart contract through an oracle. 
Or
2. Publish them on the smart contract at an intermediate phase between the registration and cast vote phases at the cost of more storage gas and additional transaction. 

The admin has an incentive to compute them correctly; otherwise, at the tallying phase, he wouldn't be able to brute-force the discrete log of the tally result. Hence, the smart contract will slash out the admin's collateral after timing out.

Kindly, let me know if you have a better idea.

**Comment by HSG88** [comment]
Very interesting, the smart contract doesn't verify the correctness of g^{y} which poses a security problem here as a voter can submit an arbitrary g^y which makes the tallying process produces something other than g^{\Sum {v_i}}. In that case, the admin won't be able to brute-force the discrete log \Sum {v_i}. Hence, a malicious voter can make a transaction that will result in unfair penalty over the admin. 

Here are few initial thoughts and the problems o resolve this issue: 
1. The smart contract calculates g^y for each voter
**Pros**: voters don't do heavy computation anymore **Cons**: the protocol scales linearly with the number of voters. 

2. The admin computes all g^{y}, stores them on the smart contract, then a dispute phase is opened for an honest voter to report invalid g^y. The smart contract recomputes g^y only once and resolves the dispute. 
Pros: In case the admin was honest, then there is no extra computation on the smart contract.
Cons: If the admin was malicious, the smart contract makes O(n) computation EC addition to resolve the dispute

3- Same as 2, but encode the off-chain computation using Merkle tree to dispute a single invalid EC addition. The same idea behind computing the tally.
Pros: same as 2,
Cons: dispute is a lot cheaper than 2

Thank you for raising this issue, and I'm gladly open for any further discussions
